apiVersion: v1
kind: Secret
metadata:
  name: agent-secret
type: Opaque
stringData:
  BETTER_AUTH_SECRET: ""
  BETTER_AUTH_URL: "http://localhost:3000"
  CORS_ORIGIN: "http://localhost:3001"
  DATABASE_URL: ""
  MODEL: ""
  API_KEY: ""
  KAFKA_BROKER: "broker:9092"